### ISSUE TITLE
Dependencies can cause "A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe''

### ISSUE THREAD

**Issue by PeterLaiAndDigital** [maiflai/gradle-scalatest#42] opened 2016-12-13 18:13 UTC
Dependending on your dependencies list, the plugin can cause a extremly large classpath to be created and thus breaking the windows limit. This will cause an error like 

"A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe''

It be nice to have a better way of handling classpaths or a better error message 

Example project with this issue. Within the dependecies.gradle if you remove all the dependencies below the line //remove all  dependencies here. the test will pass
[maiflai_test.zip](https://github.com/maiflai/gradle-scalatest/files/649737/maiflai_test.zip)

**Comment by maiflai** [comment] 2016-12-13 19:43
thanks - is this a duplicate of https://github.com/maiflai/gradle-scalatest/issues/30 ?

**Comment by tiny-cababge** [comment] 2016-12-14 10:06
Yea same thing, i'm gonna try and create a fix for this later tonight, any preference? javaexec? processbuilder?

**Comment by maiflai** [comment] 2016-12-14 10:18
I don't have access to my original PR at the moment, will check later.

I created a meta jar with the classpath embedded in the manifest. 

I did this because I'm not sure how widely suppprted the CLASSPATH environment variable is.

**Comment by tiny-cababge** [comment] 2016-12-14 10:23
can we not move all the jars to a singular dir e.g. lib and do java -cp "lib/*", rather than specifying them individually.

**Comment by maiflai** [comment] 2016-12-14 11:49
I'm not sure that classpath wildcard expansion is supported by every Java Runtime.

Setting the environment variable works for the Oracle Runtime and doesn't involve copying every dependency.

**Comment by maiflai** [comment] 2016-12-14 21:07
Looking back, my concern about fixing this upstream is related to the way that the `JavaExecHandleBuilder` builds its final command-line, and being able to write sensible tests for it.

However, I think it's almost ready for submission to the Gradle team, and hopefully this will fix the problem for a range of plugins, each of whom have their own workaround.

If you want to work around this in the meantime then I suggest the following snippet:

```groovy
test {
  doFirst {
    def cp = CollectionUtils.join(File.pathSeparator, classpath.getFiles())
    environment 'CLASSPATH', cp
    classpath = classpath.filter { false }
  }
}
```

**Comment by maiflai** [comment] 2016-12-16 08:53
I've sent https://github.com/gradle/gradle/pull/1023

**Comment by eshepelyuk** [comment] 2018-03-07 15:33
You've saved our project ! Thanks !

**Comment by maiflai** [comment] 2019-12-31 13:14
Duplicate of issue 30 and resolved in Gradle 6

**Closed by maiflai** 2019-12-31 13:14 UTC
