### ISSUE TITLE
IDEA console ANSI color render

### ISSUE THREAD

**Issue by pan3793** [maiflai/gradle-scalatest#91] opened 2021-01-22 03:29 UTC
Hi, 
I'm using this plugin on my project with IDEA, but found the issue about ANSI color when click run button from IDE.

So, should I tune some configuration to make color render correctly? Or can I disable `gradle-scalatest` ANSI color ouput?

```
Starting Gradle Daemon...
Gradle Daemon started in 684 ms

> Task :xenon-common:xenon-common-spark:compileJava UP-TO-DATE
> Task :xenon-common:xenon-common-spark:compileScala UP-TO-DATE
> Task :xenon-common:xenon-common-spark:processResources NO-SOURCE
> Task :xenon-common:xenon-common-spark:classes UP-TO-DATE
> Task :xenon-common:xenon-common-spark:jar UP-TO-DATE
> Task :xenon-ng:xenon-ng-spark:compileJava NO-SOURCE
> Task :xenon-ng:xenon-ng-spark:compileScala UP-TO-DATE
> Task :xenon-ng:xenon-ng-spark:processResources UP-TO-DATE
> Task :xenon-ng:xenon-ng-spark:classes UP-TO-DATE
> Task :xenon-ng:xenon-ng-spark:compileTestJava NO-SOURCE
> Task :xenon-ng:xenon-ng-spark:compileTestScala
> Task :xenon-ng:xenon-ng-spark:processTestResources
> Task :xenon-ng:xenon-ng-spark:testClasses
> Task :xenon-ng:xenon-ng-spark:test
[36mDiscovery starting.[0m
[36mDiscovery completed in 90 milliseconds.[0m
[36mRun starting. Expected test count is: 1[0m
10
[32mBsonTest:[0m
[32m- parse mongo shake json as bson (41 milliseconds)[0m
[36mRun completed in 194 milliseconds.[0m
[36mTotal number of tests run: 1[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
```

**Comment by pan3793** [comment] 2021-02-03 06:26
@maiflai Any suggestion?

**Comment by maiflai** [comment] 2021-02-03 07:27
I think this is a duplicate of the open issue https://github.com/maiflai/gradle-scalatest/issues/69?

In my opinion the IDE should instruct Gradle that it requires plain ASCII output, and then this plugin will respect its wishes.

Alternatively you might consider using https://github.com/helmethair-co/scalatest-junit-runner. It takes an approach that is more compatible with IDE integration.

**Closed** 2021-02-03 07:42 UTC
