### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by AceHack** [maiflai/gradle-scalatest#85] opened 2020-07-14 15:47 UTC
I don't see any recent activity around newer scala test and Gradle versions.

**Comment by maiflai** [comment] 2020-07-14 15:52
https://github.com/maiflai/gradle-scalatest/issues/83 requires an update to the README to point out that the runtime dependency changes when you upgrade.

Apart from that, I'm not aware of any issues that are caused by, or can be resolved by newer versions of Gradle or ScalaTest.

Is there a particular issue you'd like to raise please?

**Comment by maiflai** [comment] 2020-08-01 22:02
closing due to lack of response

**Closed by maiflai** 2020-08-01 22:02 UTC
