### ISSUE TITLE
No tests run using exclude tags

### ISSUE THREAD

**Issue by xanderdunn** [maiflai/gradle-scalatest#25] opened 2015-09-13 20:47 UTC
Here my entire build.gradle: 
```groovy
// scoverage = code coverage
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath 'org.scoverage:gradle-scoverage:1.0.9'
  }
}

// scalatest = unit testing framework
plugins {
  id "com.github.maiflai.scalatest" version "0.9"
}
apply plugin: 'scoverage'
repositories {
    mavenCentral()
}
apply plugin: 'scala'  // basic scala support
dependencies {
    compile 'org.scala-lang:scala-library:2.11.7'
    testCompile 'org.scalatest:scalatest_2.11:2+'
    testRuntime 'org.pegdown:pegdown:1.1.0'
    scoverage 'org.scoverage:scalac-scoverage-plugin_2.11:1.1.0', 'org.scoverage:scalac-scoverage-runtime_2.11:1.1.0'
}

apply plugin: "com.github.maiflai.scalatest"

test {
    tags {
        exclude 'org.scalatest.tags.CoverageAcceptanceTest'
        exclude 'org.scalatest.tags.UnitTest'
    }
}

testScoverage {
    tags {
        exclude 'org.scalatest.tags.NonCoverageAcceptanceTest'
    }
}
```

When I run `gradle clean && gradle test` or `gradle clean && grade testScoverage`, I see output like this:
```bash
:test
Discovery starting.
Discovery completed in 89 milliseconds.
Run starting. Expected test count is: 1
Run completed in 147 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.

BUILD SUCCESSFUL
```
In other words, it found 1 test to run, which is correct, but then it didn't actually run anything.  

It's linked to my use of exclude tags.  If I completely comment out the test{} and testScoverage{} blocks in my build.gradle, then running `gradle test` will run all of my tests, as expected.  

Why would it find tests and then not run any of them?  The tests are actually failing, so if it did actually run them then the build would fail.

**Comment by maiflai** [comment] 2015-09-14 09:20
That's odd - taking https://github.com/xanderdunn/reinforcementLearning as an example I find that `test` runs 1 test which passes.

When I uncomment the second test in `src/test/scala/ticTacToeTests.scala` it runs and fails:

```bash
:test
Discovery starting.
Discovery completed in 126 milliseconds.
Run starting. Expected test count is: 2
TicTacToeSpec:
Tic-tac-toe learning
NeuralNetSpec:
A NeuralNet
- should have greater than 79.0% X wins for Neural Net vs. Random (11 minutes, 56 seconds)
  + X won 88.485% of games 
- should have greater than 90% stalemates for Neural vs. Neural *** FAILED *** (12 minutes, 29 seconds)
  0.0 was not greater than 0.9 (ticTacToeTests.scala:79)
Run completed in 12 minutes, 29 seconds.
Total number of tests run: 2
Suites: completed 3, aborted 0
Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
TicTacToeSpec:
Tic-tac-toe learning 
- should have greater than 90% stalemates for Neural vs. Neural *** FAILED *** (12 minutes, 29 seconds)
  0.0 was not greater than 0.9 (ticTacToeTests.scala:79)
:test FAILED
```

Is this an appropriate repository to use as a working example? If so, please could you push any updates and I'll see if I can reproduce the problem.

**Comment by xanderdunn** [comment] 2015-09-14 17:28
Yeah, I get the same results that you do for master on GitHub.  

I've pushed my changes to the [unitTests branch](https://github.com/xanderdunn/reinforcementLearning/tree/unitTests).  With this code, I run `gradle clean && gradle test` and it outputs: 
```groovy
:test
Discovery starting.
Discovery completed in 94 milliseconds.
Run starting. Expected test count is: 2
Run completed in 156 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.

BUILD SUCCESSFUL
```

The most significant difference related to unit tests that I can think of is that I created custom tag classes and tagged all of my unit tests.  If I remove the exclude tag lines from my build.gradle, then it runs all the tests as expected. 

Thanks a lot for your help!

**Comment by maiflai** [comment] 2015-09-14 18:55
Sorry - is this a typo?

I think you mean that you want to _include_ `org.scalatest.tags.UnitTest`, but the current`build.gradle` marks them as _exclude_.

Perhaps this is what it should be?

```groovy
test {
    tags {
        include 'org.scalatest.tags.UnitTest' // include Unit
        exclude 'org.scalatest.tags.CoverageAcceptanceTest' // exclude Coverage
    }
}
```

I guess that scalatest is reporting a single suite to indicate the wrapping suite (the `DiscoverySuite`).

**Comment by xanderdunn** [comment] 2015-09-14 19:17
No, this is not a typo. I have two test targets: test and testScoverage. 

I want test to run nothing but those tests with the tag NonCoverageAcceptanceTest. Hence, I excluded all other test tags. 

I want testScoverage to run those tests tagged CoverageAcceptanceTest or UnitTest.

**Comment by maiflai** [comment] 2015-09-14 19:50
Hmm - yes - from the documentation I see that:

_If tags to include is not specified, then all tests except those mentioned in the tags to exclude (and in the org.scalatest.Ignore tag), will be executed_

So I agree that excluding those two tags should have the desired effect.

I am however getting very strange results running the tests by hand (i.e. without Gradle).

Scalatest appears to randomly detect tests when using the `PS` argument which is intended to enable parallel execution of Suites (I notice that you are using `ParallelTestExecution` in order to enable this at a test level rather than Suite).

`gradle clean test -i` prints the command line before running the test. Can you remove the `PS` argument locally, run the command and see if this helps? Unfortunately `PS` is always specified, it's just the number which can currently be controlled...

**Comment by maiflai** [comment] 2015-09-14 20:01
And it seems that `Pn` works, it's just `PSn` that doesn't.

Sorry, I'll have to pick this up tomorrow, I suspect it will require an update to the plugin.

Please could you confirm these findings if you get a mo?

Thanks,
Stu

**Comment by maiflai** [comment] 2015-09-15 19:33
I reviewed the git log - `PS` is used to ensure that the tests are reported in a sane manner when they are run in parallel. I don't think I can remove it.

I did remove the use of `ParallelTestExecution` in your tests and the build seems to fail reliably. Are you ok with this workaround?

I think this is actually an issue in the underlying scalatest library. I imagine you'd rather continue with working on the problem you're trying to solve, rather than debugging a tool? I'm happy to chase this down with the scalatest guys, unless you fancy it...

Cheers,
Stu

**Comment by xanderdunn** [comment] 2015-09-15 19:53
@maiflai Thanks so much for your help!  Yeah, this is very helpful.  It's a huge performance gain for me to be able to run the tests in parallel, but as a temporary workaround I'll run them without `ParallelTestExecution`.

It would be awesome if you followed up with the scalatest team, thanks!

Since this doesn't appear to be an issue with gradle-scalatest, shall I close this?

**Comment by maiflai** [comment] 2015-09-18 19:12
Thanks - closing this issue now that I've raised https://github.com/scalatest/scalatest/issues/706

**Closed by maiflai** 2015-09-18 19:12 UTC

**Comment by xanderdunn** [comment] 2015-09-18 19:15
@maiflai Thanks!

**Comment by jeksmith** [comment] 2020-06-26 05:30
Greetings. I know this issue was closed almost 5 years ago, but it is currently a thorn in our side. And still a problem even with Scalatest 3.2.0. I think we'd be happy just risking it with -P instead of -PS. @maiflai Any way to get that with the current version 0.26? Or would that require a code change? 
Thanks.
